### PR TITLE
upgrade flapdoodle process to latest

### PR DESCRIPTION
**Pull request by noam-almog**
Flapdoodle process --> latest

Do not merge yet till embedded mongo will release a newer version with it.

### CODE REVIEW

**Comment by viliusl** [comment]
@noam-almog it seems latest flapdoodle boundary dropped support for java 1.7. Now question if we want to do the same. We can up major version and drop support for 1.7 java, but is it smth we want to do? Given we have to add mappings for new mysql versions we might end-up supporting 2 versions of library which I'm not sure I want to do right now.

Not really sure.

**Comment by noam-almog** [comment]
@viliusl we have time till embedded mongo will move to the new library anyhow.
From what i see, if we want to be compatible to all the safest thing is to stay with the 1.x versions.
We bump major version and say that newer versions will need java 8, if you want java 7 use the older version.

btw, as long as both versions have compatible api it's not that hard to support two of those builds in maven (I saw some dependencies that does that)

**Comment by viliusl** [comment]
Ok, maybe kiss it and move to java 8.

On the other note - maybe we should not have 'Do not merge yet till embedded mongo will release a newer version with it.' but instead fix version of wix-embedded-mysql in fw and then manage versions explicitly there?:)

**Comment by noam-almog** [comment]
basically it's 'do not merge till we decide we want to merge ' 😀

**Pull request closed without merging**
