### PR TITLE
Enable configuration of download cache dir, temp dir

### PR DESCRIPTION
**Pull request by viliusl**

### CODE REVIEW

**Comment by viliusl** [comment]
@noam-almog please - most importantly does it make sense:)

My idea is:
 - tempDir - it's a runtime configuration of mysql, so moved it to MysqldConfig;
 - downloadCacheDir - it's download/prepare setting, so added to DownloadConfig and planning to add there additional settings - url, proxy, etc.

Given I will want to expose additional settings that are neither runtime nor download settings, I can easily do it via AdditionalConfig.

**Comment by noam-almog** [comment]
@viliusl not sure about the logic, all download and runtime should probably sit together.
btw, does the user must specify this in the builder right now ? i think this should be optional.

**Comment by ittaiz** [comment]
Not really following but noticed the "all download and runtime should
probably sit together" part and wanted to chime in and say we'll probably
need to use the download part separately from the runtime. Treat it sort of
like a maven dependency. Maybe it's completely irrelevant but wanted to
give my 2c

**Comment by noam-almog** [comment]
@ittaiz i'll rephrase, target dir, download dir and all of the mechanics of downloading and extracting should be in the same place

**Comment by ittaiz** [comment]
sounds good

**Comment by viliusl** [comment]
@noam-almog yes/no/maybe.
Runtime: cwd (tempDir), port, user, ...;
Download: cacheDir, url, proxy, download timeout.

This was my motivation to add tempDir to an existing config and move download related stuff to a new one.

Otherwise `DownloadConfig` is optional.

**Comment by noam-almog** [comment]
@viliusl I would move temp dir to the download config, but that's just my opinion.
the DSL is good enough for people to find it anyhow :)

**Pull request merged**
