### PR TITLE
Add support for mysql@8

### PR DESCRIPTION
**Pull request by viliusl**

### CODE REVIEW

**Comment by dmcwhorter** [comment]
tested this branch with Mysql 8.0.13 on MacOS 10.13, everything seems to work fine

**Comment by viliusl** [comment]
@dmcwhorter - same here, but I want to make ci happy as well:/

**Comment by privettoli** [comment]
Would love to see it in the master branch. Good job! @viliusl

**Comment by Omelianchuk** [comment]
> 
> 
> @dmcwhorter - same here, but I want to make ci happy as well:/

Looks like Travis has problem with to long log in build 693.4 and just stuck in 693.3. Is this relates to your changes? Maybe changing log level to INFO will solve first issue?

**Comment by ngueno** [comment]
Hi there folks, how are you doing? 
Any plans of including this on 4.2.1 release or any soon?

**Comment by ngueno** [comment]
Hi there @viliusl , how are you doing?
Any plans of including this on 4.2.1 release or any soon?

It would be awesome to have the version 8.x available on master

**Comment by ngueno** [comment]
@dmcwhorter @viliusl @privettoli @Omelianchuk Hey folks! How are you doing? 

It would be awesome to have this on master branch :) Do you have any plans to release it any soon?

**Comment by viliusl** [comment]
Released in version 4.5.0

**Pull request merged**
