### PR TITLE
OSX Firewall prob fix

### PR DESCRIPTION
**Pull request by viliusl**
https://github.com/wix/embedded-my-sql/issues/11

@maximn, @noam-almog could you try it locally with fw enabled - to see if this fixed the problem.

I'm not yet sure about actual design - maybe I will move bindPort to different place or rename it, but just want to get your feedback on a fix.

On normal machines loopback address and localhost do match and map to 127.0.0.1, but not on mine and @maximn. So you might have to provide explicit 127.0.0.1 both in mysqld config and in jdbc url you have in app config.

### CODE REVIEW

**Comment by noam-almog** [comment]
@viliusl sorry to spoil the party, checkouted out the branch and ran maven and got a warning...

**Comment by viliusl** [comment]
One warning or multiple? Fun fact - I'm not getting warnings. In a embedded mongo issue I pasted guy wrote that it went away:/

**Comment by noam-almog** [comment]
I saw one and then it was stuck for some reason.

**Comment by maximn** [comment]
When running mvn install on this project I'm getting the FW warnings.
It takes very long time and it stuck during the tests.

**Comment by viliusl** [comment]
Ok, so worked just for me. Will see what could be done about fixed extract
folder.

On Mon, Jun 15, 2015 at 11:09 AM, Maxim Novak <notifications@github.com>
wrote:

> When running mvn install on this project I'm getting the FW warnings.
> It takes very long time and it stuck during the tests.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/pull/21#issuecomment-111973347>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania

**Comment by maximn** [comment]
Tried again now, getting this error-
CustomConfigurationTest>IntegrationTest.startAndVerifyDatabase:24->IntegrationTest.startAndVerify:31 » IO

**Comment by viliusl** [comment]
Nope, did not work

**Comment by michaelahlers** [comment]
I'm encountering and can't resolve this issue. Have there been any new developments on this?

**Pull request closed without merging**
