### PR TITLE
Changed timeout, timeout error code and made timeout configurable

### PR DESCRIPTION
**Pull request by viliusl**
in relation to issue #66

### CODE REVIEW

**Comment by viliusl** [comment]
@noam-almog I would appreciate a code review, as there are some changes of which I'm not really confident. Will not tell which ones - no spoilers:)

**Comment by noam-almog** [comment]
@viliusl may i suggest a different approach, timeout is not really a configuration value for the config builder but something related to process management.
I would use a default timeout and add another api for start that will allow the user to override the default value.
```
    anEmbeddedMySql(...).start
    anEmbeddedMySql(...).start(timeout = 5.seconds)
```
WDYT ?

**Comment by viliusl** [comment]
@noam-almog - the more I think about it the less I like it:/

your suggestion: my first question would be what does it apply to? whole startup? with download? in practice no, but from api it would seem like that.

in my version it's more scoped to mysqld (MysqldConfig), but it's not true as well, as it applies to 2 things:
 - mysqld startup;
 - preparation of mysql (sys schema);

In that regards I like mine a bit more, but it's still terrible. Options:
 - drop customisation of timeout altogether just increase it to 60 seconds;
 - leave it as it is;
 - expand it to sub-config like:
```
aMysqldConfig(v5_6_latest)
      .withPort(1111)
        .withTimeout(mysqldTimeouts()
            .withStartupTimeout(30)
            .withInitTimeout(30)
            .build())
      .build()
```

or 

```
aMysqldConfig(v5_6_latest)
      .withPort(1111)
      .withStartupTimeout(30)
      .withInitTimeout(30)
      .build()
```

maybe just up timeout and delay customization?

**Comment by mosheeshel** [comment]
Sorry for butting in on this, but I had a look at the code and had @viliusl same thought, there is just no elegant place to put this configuration, so I don't know which object to add these as properties to.
But I do like the addition of withXTimeout for the various elements (http connection to repo, download time, install length, startup length, etc) to the main builder.

As a side note, can we look for the cause of the timeout ? In our observations in most cases 30 seconds is more than enough, just for some instances it seems to take much longer for some unknown reason.

**Comment by viliusl** [comment]
@mosheeshel - ok, so I added withTimeout() to MysqldConfig - this now controls init, startup, shutdown timeouts. This is not perfect, but it's extensible (given you want control those timeouts separately) api-wise.

In regards to other timeouts (connect, download...) - afaik these should be extended in a different way to avoid huge builder with random properties problem. My vision is to have sub-configs - repository, network where those timeouts would go. I have couple of issues open (#65 - repository config), #54 - network config that will push me in deeper nesting of configs, but oh well - I knew the day will come.

btw - I could not reproduce issue locally - tried with centos on vm - no awail. I will add comment to original issue, but for now:
 - you (users) will have clearer error given timeout occured during init, startup, shutdown;
 - you (users) will be able to change timeout - increase if needed.

So it's a progress:)

**Comment by viliusl** [comment]
Ok, missed a thing:/ fix in #73

**Pull request merged**
