### PR TITLE
Mysql download and extract

### LINKED ISSUE #107: Allow using library in hermetic environments
We want to use wix-embedded-mysql in [Bazel](bazel.build) which strongly encourages you to have tests which are isolated from the internet.
For that matter we want to allow preparing the installer (downloading/extracting) before the actual test run (in Bazel such downloads should happen in the `fetch` phase).
As agreed with @viliusl I'll add a cli entry point for this which will accept a cache dir, base url and version.
I've started working on this but  general public inputs are always welcomed.

### PR DESCRIPTION
**Pull request by ittaiz**
this fixes #107 
@viliusl the test now also uses `java -jar` to protect from regressions to the maven assembly plugin.

### CODE REVIEW

**Comment by ittaiz** [comment]
Yay! We have a green build :)

**Comment by viliusl** [comment]
Thanks @ittaiz - looks very nice and imho ready to be merged except: readme - links to files are broken (as you moved code to main module) + new module (download-and-extract) has no docs - imho it deserves at least a section in main readme - wdyt?

**Comment by ittaiz** [comment]
Definitely agree. Sorry for forgetting about it. I'll add it tonight.

**Comment by ittaiz** [comment]
@viliusl readme updated. Would appreciate your feedback.

**Comment by viliusl** [comment]
@ittaiz thanks, merged - will release/publish shortly

**Comment by ittaiz** [comment]
Thanks!

**Comment by viliusl** [comment]
version 2.2.9 released, should be available via central shortly.

**Pull request merged**
